#!/bin/bash

BASE_DIR=$(dirname $(readlink -f $0))
EN_CONF=$BASE_DIR/data/planet.english.ini
BG_CONF=$BASE_DIR/data/planet.bulgarian.ini

pushd $BASE_DIR

source ~/virtualenvs/planet.sofiavalley.com/bin/activate

$BASE_DIR/libs/venus/planet.py $EN_CONF
# first upload CSS and manually set Mime-Type b/c Magic guesses it wrong
s3cmd sync -c $BASE_DIR/data/s3.cfg -v -m text/css -P /tmp/svplanet/english/html/*.css s3://planet.sofiavalley.com/

# then update everything else
s3cmd sync -c $BASE_DIR/data/s3.cfg -v -P /tmp/svplanet/english/html/* s3://planet.sofiavalley.com/

#$BASE_DIR/libs/venus/planet.py $BG_CONF
# todo: upload

popd $BASE_DIR
