#!/bin/bash

BASE_DIR=$(dirname $(readlink -f $0))
EN_CONF=$BASE_DIR/data/planet.english.ini
BG_CONF=$BASE_DIR/data/planet.bulgarian.ini

echo "Checking for ephemeral storage configuration"
for ef in `curl -m 5 http://169.254.169.254/latest/meta-data/block-device-mapping/ 2>/dev/null | grep ephemeral`; do
    disk=`curl http://169.254.169.254/latest/meta-data/block-device-mapping/$ef 2>/dev/null`

    # check if /tmp is already mounted (assume on ephemeral storage)
    if [ `mount | grep -c "/tmp "` == "0" ]; then
        echo "/tmp not mounted"

        echo "Unmounting /dev/$disk"
        sudo umount -f /dev/$disk

        echo "mkfs /dev/$disk"
        sudo mkfs.ext4 -q /dev/$disk

        echo "Mounting /dev/$disk on /tmp"
        sudo mount -t ext4 /dev/$disk /tmp
        sudo chmod 1777 /tmp
    else
        echo "/tmp is already mounted"
    fi
done


pushd $BASE_DIR

# update local copy
git pull origin master && git fetch --tags

# activate virtualenv. NB: name is hard-coded
source ~/.virtualenvs/planet.sofiavalley.com/bin/activate


# update planet and push contents
$BASE_DIR/libs/venus/planet.py $EN_CONF

# first upload CSS and manually set Mime-Type b/c Magic guesses it wrong
s3cmd sync -c $BASE_DIR/data/s3.cfg -v -m text/css -P /tmp/svplanet/english/html/*.css s3://planet.sofiavalley.com/

# then update everything else
s3cmd sync -c $BASE_DIR/data/s3.cfg -v -P /tmp/svplanet/english/html/* s3://planet.sofiavalley.com/


# update bulgarian version of planet
#$BASE_DIR/libs/venus/planet.py $BG_CONF
# todo: upload

popd $BASE_DIR
