#!/bin/bash

if [ -n "$OPENSHIFT_HOMEDIR" ]; then
    source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
    export PYTHON_EGG_CACHE=$OPENSHIFT_DATA_DIR/.python-eggs

    EN_CONF=$OPENSHIFT_REPO_DIR/data/planet.english.ini
    BG_CONF=$OPENSHIFT_REPO_DIR/data/planet.bulgarian.ini

    $OPENSHIFT_REPO_DIR/libs/venus/planet.py $EN_CONF
    s3cmd sync -v --acl-public /tmp/svplanet/english/html/* s3://planet.sofiavalley.com/

#    $OPENSHIFT_REPO_DIR/libs/venus/planet.py $BG_CONF
fi
